### ISSUE TITLE
Some figures are missing

### ISSUE THREAD

**Issue by toshohirasawa** [oasisresearchlab/context24#3]
For your information, some figures seem missing from the `figures-tables` directory.

```
akamatsulab-Whvj4Tjxl - FIG 2A not found.
akamatsulab-Whvj4Tjxl - FIG 2B not found.
akamatsulab-Whvj4Tjxl - FIG 2C not found.
akamatsulab-Whvj4Tjxl - FIG 2D not found.
akamatsulab-Whvj4Tjxl - FIG 2E not found.
akamatsulab-Whvj4Tjxl - FIG 2F not found.
akamatsulab-Whvj4Tjxl - FIG 2G not found.
akamatsulab-B7UPmuzgg - FIG 5.4A not found.
dg-social-media-polarization-AQy-nbEwf - FIG 2 not found.
```

**Comment by joelchan** [comment]
Thank you for catching this! We caught the missing figures for `akamatsulab-Whvj4Tjxl` (which come from the citekey `alfonzomendez2022dual`, but missed the missing FIG 2 for `dg-social-media-polarization-AQy-nbEwf`. 

Working on adding them (along with a fresh batch of ~100 more claims as training data for Task 1) by ~tomorrrow!

**Comment by joelchan** [comment]
@toshohirasawa FYI closing this, addressed both `northBattleBritainAnalyzing2021` and `alfonzomendez2022dual` with latest update. thanks for flagging!
