### ISSUE TITLE
Report/paper submission

### ISSUE THREAD

**Issue by ryabhmd** [oasisresearchlab/context24#7]
Hello 😊

Could you please elaborate on the paper/report that we can submit as participants in this shared task? 

More specifically, we were wondering whether the same submission information for the general SDP workshop apply in terms of using the ACL template, and if there are any restrictions in terms of submitting a long vs. short paper.
Also, will these papers be published in the workshop proceedings?  

Thanks a lot!

**Comment by aakanksha19** [comment]
Hi,

Thanks for checking in with us about this! We plan to follow the same submission requirements and process as the SDP 2024 workshop (https://sdproc.org/2024/cfp.html). This means that submissions should:
- Use the ACL template
- Can be long papers (8 page limit) or short papers (4 page limit)
- Can use one extra page in the camera ready version to address any comments

These papers will be published in the workshop proceedings. The submission portal will be available soon at [this link](https://openreview.net/group?id=aclweb.org/ACL/2024/Workshop/SDProc) and will be open until June 17.

Let us know if there are more questions!
